### ISSUE TITLE
Incorrect default import/export

### ISSUE THREAD

**Issue by justintaddei** [electronjs/electron-compilers#86]
Not sure if this is a bug or if I'm doing something wrong here.

The `ws` module  exports `WebSocket` like so:
```javascript
// `ws` module
module.exports = WebSocket;
```
I'm importing `WebSocket` from the `ws` module like so:
```typescript
// server.ts
import 'WebSocket' from 'ws';

const Server  = new WebSocket.Server(options);
```
Seems fine, right?
Well, it is being compiled to the following:
```javascript
var ws_1 = require("ws");

var Server = new ws_1.default.Server(options);
```

The problem is that `ws_1.default` is `undefined`. It should be compiled to `ws_1.Server`, should it not?

**Comment by MarshallOfSound** [comment]
> should it not?

This is how typescript works, when you do `import foo from 'bar'` it expects to import the default export from `bar` and name it `foo`.  Because `ws` doesn't have a default export it will fail.

You should be using `import * as WebSocket from 'ws'`

See https://www.typescriptlang.org/docs/handbook/modules.html for more info
